// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/paulusrobin/leaf-utilities/logger/logger (interfaces: Logger,StandardLogger)

// Package mock_leafLogger is a generated GoMock package.
package mock_leafLogger

import (
	io "io"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	log "github.com/labstack/gommon/log"
	leafLogger "github.com/paulusrobin/leaf-utilities/logger/logger"
)

// MockLogger is a mock of Logger interface.
type MockLogger struct {
	ctrl     *gomock.Controller
	recorder *MockLoggerMockRecorder
}

// MockLoggerMockRecorder is the mock recorder for MockLogger.
type MockLoggerMockRecorder struct {
	mock *MockLogger
}

// NewMockLogger creates a new mock instance.
func NewMockLogger(ctrl *gomock.Controller) *MockLogger {
	mock := &MockLogger{ctrl: ctrl}
	mock.recorder = &MockLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogger) EXPECT() *MockLoggerMockRecorder {
	return m.recorder
}

// Debug mocks base method.
func (m *MockLogger) Debug(arg0 leafLogger.Message) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Debug", arg0)
}

// Debug indicates an expected call of Debug.
func (mr *MockLoggerMockRecorder) Debug(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Debug", reflect.TypeOf((*MockLogger)(nil).Debug), arg0)
}

// Error mocks base method.
func (m *MockLogger) Error(arg0 leafLogger.Message) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Error", arg0)
}

// Error indicates an expected call of Error.
func (mr *MockLoggerMockRecorder) Error(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockLogger)(nil).Error), arg0)
}

// Info mocks base method.
func (m *MockLogger) Info(arg0 leafLogger.Message) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Info", arg0)
}

// Info indicates an expected call of Info.
func (mr *MockLoggerMockRecorder) Info(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Info", reflect.TypeOf((*MockLogger)(nil).Info), arg0)
}

// StandardLogger mocks base method.
func (m *MockLogger) StandardLogger() leafLogger.StandardLogger {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StandardLogger")
	ret0, _ := ret[0].(leafLogger.StandardLogger)
	return ret0
}

// StandardLogger indicates an expected call of StandardLogger.
func (mr *MockLoggerMockRecorder) StandardLogger() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StandardLogger", reflect.TypeOf((*MockLogger)(nil).StandardLogger))
}

// Warn mocks base method.
func (m *MockLogger) Warn(arg0 leafLogger.Message) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Warn", arg0)
}

// Warn indicates an expected call of Warn.
func (mr *MockLoggerMockRecorder) Warn(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Warn", reflect.TypeOf((*MockLogger)(nil).Warn), arg0)
}

// MockStandardLogger is a mock of StandardLogger interface.
type MockStandardLogger struct {
	ctrl     *gomock.Controller
	recorder *MockStandardLoggerMockRecorder
}

// MockStandardLoggerMockRecorder is the mock recorder for MockStandardLogger.
type MockStandardLoggerMockRecorder struct {
	mock *MockStandardLogger
}

// NewMockStandardLogger creates a new mock instance.
func NewMockStandardLogger(ctrl *gomock.Controller) *MockStandardLogger {
	mock := &MockStandardLogger{ctrl: ctrl}
	mock.recorder = &MockStandardLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStandardLogger) EXPECT() *MockStandardLoggerMockRecorder {
	return m.recorder
}

// Debug mocks base method.
func (m *MockStandardLogger) Debug(arg0 ...interface{}) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Debug", varargs...)
}

// Debug indicates an expected call of Debug.
func (mr *MockStandardLoggerMockRecorder) Debug(arg0 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Debug", reflect.TypeOf((*MockStandardLogger)(nil).Debug), arg0...)
}

// Debugf mocks base method.
func (m *MockStandardLogger) Debugf(arg0 string, arg1 ...interface{}) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Debugf", varargs...)
}

// Debugf indicates an expected call of Debugf.
func (mr *MockStandardLoggerMockRecorder) Debugf(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Debugf", reflect.TypeOf((*MockStandardLogger)(nil).Debugf), varargs...)
}

// Debugj mocks base method.
func (m *MockStandardLogger) Debugj(arg0 log.JSON) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Debugj", arg0)
}

// Debugj indicates an expected call of Debugj.
func (mr *MockStandardLoggerMockRecorder) Debugj(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Debugj", reflect.TypeOf((*MockStandardLogger)(nil).Debugj), arg0)
}

// Error mocks base method.
func (m *MockStandardLogger) Error(arg0 ...interface{}) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Error", varargs...)
}

// Error indicates an expected call of Error.
func (mr *MockStandardLoggerMockRecorder) Error(arg0 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockStandardLogger)(nil).Error), arg0...)
}

// Errorf mocks base method.
func (m *MockStandardLogger) Errorf(arg0 string, arg1 ...interface{}) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Errorf", varargs...)
}

// Errorf indicates an expected call of Errorf.
func (mr *MockStandardLoggerMockRecorder) Errorf(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Errorf", reflect.TypeOf((*MockStandardLogger)(nil).Errorf), varargs...)
}

// Errorj mocks base method.
func (m *MockStandardLogger) Errorj(arg0 log.JSON) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Errorj", arg0)
}

// Errorj indicates an expected call of Errorj.
func (mr *MockStandardLoggerMockRecorder) Errorj(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Errorj", reflect.TypeOf((*MockStandardLogger)(nil).Errorj), arg0)
}

// Fatal mocks base method.
func (m *MockStandardLogger) Fatal(arg0 ...interface{}) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Fatal", varargs...)
}

// Fatal indicates an expected call of Fatal.
func (mr *MockStandardLoggerMockRecorder) Fatal(arg0 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fatal", reflect.TypeOf((*MockStandardLogger)(nil).Fatal), arg0...)
}

// Fatalf mocks base method.
func (m *MockStandardLogger) Fatalf(arg0 string, arg1 ...interface{}) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Fatalf", varargs...)
}

// Fatalf indicates an expected call of Fatalf.
func (mr *MockStandardLoggerMockRecorder) Fatalf(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fatalf", reflect.TypeOf((*MockStandardLogger)(nil).Fatalf), varargs...)
}

// Fatalj mocks base method.
func (m *MockStandardLogger) Fatalj(arg0 log.JSON) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Fatalj", arg0)
}

// Fatalj indicates an expected call of Fatalj.
func (mr *MockStandardLoggerMockRecorder) Fatalj(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fatalj", reflect.TypeOf((*MockStandardLogger)(nil).Fatalj), arg0)
}

// Info mocks base method.
func (m *MockStandardLogger) Info(arg0 ...interface{}) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Info", varargs...)
}

// Info indicates an expected call of Info.
func (mr *MockStandardLoggerMockRecorder) Info(arg0 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Info", reflect.TypeOf((*MockStandardLogger)(nil).Info), arg0...)
}

// Infof mocks base method.
func (m *MockStandardLogger) Infof(arg0 string, arg1 ...interface{}) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Infof", varargs...)
}

// Infof indicates an expected call of Infof.
func (mr *MockStandardLoggerMockRecorder) Infof(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Infof", reflect.TypeOf((*MockStandardLogger)(nil).Infof), varargs...)
}

// Infoj mocks base method.
func (m *MockStandardLogger) Infoj(arg0 log.JSON) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Infoj", arg0)
}

// Infoj indicates an expected call of Infoj.
func (mr *MockStandardLoggerMockRecorder) Infoj(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Infoj", reflect.TypeOf((*MockStandardLogger)(nil).Infoj), arg0)
}

// Instance mocks base method.
func (m *MockStandardLogger) Instance() interface{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Instance")
	ret0, _ := ret[0].(interface{})
	return ret0
}

// Instance indicates an expected call of Instance.
func (mr *MockStandardLoggerMockRecorder) Instance() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Instance", reflect.TypeOf((*MockStandardLogger)(nil).Instance))
}

// Level mocks base method.
func (m *MockStandardLogger) Level() log.Lvl {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Level")
	ret0, _ := ret[0].(log.Lvl)
	return ret0
}

// Level indicates an expected call of Level.
func (mr *MockStandardLoggerMockRecorder) Level() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Level", reflect.TypeOf((*MockStandardLogger)(nil).Level))
}

// Log mocks base method.
func (m *MockStandardLogger) Log(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Log", arg0)
}

// Log indicates an expected call of Log.
func (mr *MockStandardLoggerMockRecorder) Log(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Log", reflect.TypeOf((*MockStandardLogger)(nil).Log), arg0)
}

// Output mocks base method.
func (m *MockStandardLogger) Output() io.Writer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Output")
	ret0, _ := ret[0].(io.Writer)
	return ret0
}

// Output indicates an expected call of Output.
func (mr *MockStandardLoggerMockRecorder) Output() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Output", reflect.TypeOf((*MockStandardLogger)(nil).Output))
}

// Panic mocks base method.
func (m *MockStandardLogger) Panic(arg0 ...interface{}) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Panic", varargs...)
}

// Panic indicates an expected call of Panic.
func (mr *MockStandardLoggerMockRecorder) Panic(arg0 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Panic", reflect.TypeOf((*MockStandardLogger)(nil).Panic), arg0...)
}

// Panicf mocks base method.
func (m *MockStandardLogger) Panicf(arg0 string, arg1 ...interface{}) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Panicf", varargs...)
}

// Panicf indicates an expected call of Panicf.
func (mr *MockStandardLoggerMockRecorder) Panicf(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Panicf", reflect.TypeOf((*MockStandardLogger)(nil).Panicf), varargs...)
}

// Panicj mocks base method.
func (m *MockStandardLogger) Panicj(arg0 log.JSON) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Panicj", arg0)
}

// Panicj indicates an expected call of Panicj.
func (mr *MockStandardLoggerMockRecorder) Panicj(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Panicj", reflect.TypeOf((*MockStandardLogger)(nil).Panicj), arg0)
}

// Prefix mocks base method.
func (m *MockStandardLogger) Prefix() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Prefix")
	ret0, _ := ret[0].(string)
	return ret0
}

// Prefix indicates an expected call of Prefix.
func (mr *MockStandardLoggerMockRecorder) Prefix() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Prefix", reflect.TypeOf((*MockStandardLogger)(nil).Prefix))
}

// Print mocks base method.
func (m *MockStandardLogger) Print(arg0 ...interface{}) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Print", varargs...)
}

// Print indicates an expected call of Print.
func (mr *MockStandardLoggerMockRecorder) Print(arg0 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Print", reflect.TypeOf((*MockStandardLogger)(nil).Print), arg0...)
}

// Printf mocks base method.
func (m *MockStandardLogger) Printf(arg0 string, arg1 ...interface{}) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Printf", varargs...)
}

// Printf indicates an expected call of Printf.
func (mr *MockStandardLoggerMockRecorder) Printf(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Printf", reflect.TypeOf((*MockStandardLogger)(nil).Printf), varargs...)
}

// Printj mocks base method.
func (m *MockStandardLogger) Printj(arg0 log.JSON) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Printj", arg0)
}

// Printj indicates an expected call of Printj.
func (mr *MockStandardLoggerMockRecorder) Printj(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Printj", reflect.TypeOf((*MockStandardLogger)(nil).Printj), arg0)
}

// Println mocks base method.
func (m *MockStandardLogger) Println(arg0 ...interface{}) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Println", varargs...)
}

// Println indicates an expected call of Println.
func (mr *MockStandardLoggerMockRecorder) Println(arg0 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Println", reflect.TypeOf((*MockStandardLogger)(nil).Println), arg0...)
}

// SetHeader mocks base method.
func (m *MockStandardLogger) SetHeader(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetHeader", arg0)
}

// SetHeader indicates an expected call of SetHeader.
func (mr *MockStandardLoggerMockRecorder) SetHeader(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHeader", reflect.TypeOf((*MockStandardLogger)(nil).SetHeader), arg0)
}

// SetLevel mocks base method.
func (m *MockStandardLogger) SetLevel(arg0 log.Lvl) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetLevel", arg0)
}

// SetLevel indicates an expected call of SetLevel.
func (mr *MockStandardLoggerMockRecorder) SetLevel(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLevel", reflect.TypeOf((*MockStandardLogger)(nil).SetLevel), arg0)
}

// SetOutput mocks base method.
func (m *MockStandardLogger) SetOutput(arg0 io.Writer) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetOutput", arg0)
}

// SetOutput indicates an expected call of SetOutput.
func (mr *MockStandardLoggerMockRecorder) SetOutput(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetOutput", reflect.TypeOf((*MockStandardLogger)(nil).SetOutput), arg0)
}

// SetPrefix mocks base method.
func (m *MockStandardLogger) SetPrefix(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetPrefix", arg0)
}

// SetPrefix indicates an expected call of SetPrefix.
func (mr *MockStandardLoggerMockRecorder) SetPrefix(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPrefix", reflect.TypeOf((*MockStandardLogger)(nil).SetPrefix), arg0)
}

// Warn mocks base method.
func (m *MockStandardLogger) Warn(arg0 ...interface{}) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Warn", varargs...)
}

// Warn indicates an expected call of Warn.
func (mr *MockStandardLoggerMockRecorder) Warn(arg0 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Warn", reflect.TypeOf((*MockStandardLogger)(nil).Warn), arg0...)
}

// Warnf mocks base method.
func (m *MockStandardLogger) Warnf(arg0 string, arg1 ...interface{}) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Warnf", varargs...)
}

// Warnf indicates an expected call of Warnf.
func (mr *MockStandardLoggerMockRecorder) Warnf(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Warnf", reflect.TypeOf((*MockStandardLogger)(nil).Warnf), varargs...)
}

// Warnj mocks base method.
func (m *MockStandardLogger) Warnj(arg0 log.JSON) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Warnj", arg0)
}

// Warnj indicates an expected call of Warnj.
func (mr *MockStandardLoggerMockRecorder) Warnj(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Warnj", reflect.TypeOf((*MockStandardLogger)(nil).Warnj), arg0)
}
